// =============================================================
// DATA PROVENANCE REGISTRY
// -------------------------------------------------------------
// Every piece of mock data in this prototype is annotated with
// a provenance entry — where it should come from in production,
// in which tour-lifecycle phase, and through which mechanism.
//
// UI components read from this registry:
//   <MockTag />            — tiny inline "(mock)" indicator with click-popup
//   <MockBadge />          — section-level "Mock" chip with hover tooltip
//   <DataSourcesPanel />   — per-page collapsible listing all sources
//
// Phases mirror tour-management-deep-research.md §2.
// =============================================================

export type RealSource =
  | 'manual_entry'        // user types it into the app
  | 'csv_import'          // bulk-imported spreadsheet
  | 'ai_extraction'       // parsed from uploaded PDF/email by Claude
  | 'document_upload'     // file uploaded as-is and stored in R2/S3
  | 'external_api'        // integration: booking system, HET Hub, weather
  | 'derived'             // computed from other entities
  | 'system';             // auto-generated by the app

export type LifecyclePhase =
  | 'booking'        // months/years out — agent + manager
  | 'advance'        // 8-12 weeks out — PM contacting venue PMs
  | 'rehearsal'      // 1-4 weeks before kickoff
  | 'show_day'       // every day on the road
  | 'settlement'     // every night + post-tour
  | 'ongoing';       // anytime

export interface ProvenanceArtifact {
  /** Display label for the link. */
  label: string;
  /** URL (relative or absolute) — pointing to the mock file in /public. */
  url: string;
  /** Optional kind for icon choice. */
  kind?: 'csv' | 'doc' | 'pdf' | 'email' | 'image' | 'json';
}

export interface Provenance {
  source: string;       // short label, e.g. "Booking agent deal memo"
  realSource: RealSource;
  phase: LifecyclePhase;
  detail?: string;      // long-form: how the real-system flow works
  /** Mock source documents that would have populated this in production. */
  artifacts?: ProvenanceArtifact[];
}

// =============================================================
// Provenance by entity / data category
// =============================================================

export const sources = {
  // ----- Top-level tour shell ---------------------------------
  organization: {
    source: 'Org admin setup',
    realSource: 'manual_entry',
    phase: 'ongoing',
    detail:
      'Created when the artist team / management company first signs up. Top of the data tree.',
  },
  tour: {
    source: 'TM setup wizard after agent hand-off',
    realSource: 'manual_entry',
    phase: 'booking',
    detail:
      'Agent emails the deal memo. TM enters the tour shell (name, artist, dates, status) into the hub. v2: import directly from booking platforms (Eventric, Prism).',
  },
  tour_route: {
    source: 'Booking agent deal memos + routing spreadsheet',
    realSource: 'manual_entry',
    phase: 'booking',
    detail:
      'The agent sells the shows and emails a routing spreadsheet with dates, cities, venues, capacities, and deal terms. The TM enters this into the hub manually in v1 (or imports the CSV). The rider PDF never contains a route — it is a per-show requirements document.',
    artifacts: [
      { label: 'Mock 7-day route (Mexico leg)', url: '/mock-tour-route-mexico-7day.csv', kind: 'csv' },
    ],
  },
  leg: {
    source: 'Routing decisions by agent + TM',
    realSource: 'manual_entry',
    phase: 'booking',
    detail:
      'Tours are usually broken into legs by routing or by month. Defined when the TM sets up the calendar.',
  },
  day: {
    source: 'Auto-generated from tour date range',
    realSource: 'derived',
    phase: 'booking',
    detail:
      'Every date between start and end gets a Day row. DayType defaults to "hold" until TM/PM sets it. Shows attach when DayType=show.',
  },
  day_weather: {
    source: 'Weather API (OpenWeather / Tomorrow.io)',
    realSource: 'external_api',
    phase: 'show_day',
    detail: 'Fetched the morning of the show. Surfaced on day sheets.',
  },
  venue: {
    source: 'Reusable venue database',
    realSource: 'manual_entry',
    phase: 'advance',
    detail:
      'Venues are a global entity, reused across tours. Master Tour has 15k+ venues — your hub builds its own venue DB as TMs use it.',
  },

  // ----- People -----------------------------------------------
  person: {
    source: 'Reusable person database',
    realSource: 'manual_entry',
    phase: 'advance',
    detail:
      'Persons are global — a person reused across tours keeps the same record. TourPerson links Person → Tour + Role + Group + Tags + DateRange.',
  },
  tour_person: {
    source: 'TM/PM crew roster build-out',
    realSource: 'manual_entry',
    phase: 'advance',
    detail:
      'Three input paths in v1: (1) search/create, (2) CSV import, (3) copy from previous tour. The copy-from-previous flow is what gets TMs to switch off Master Tour.',
  },
  group: {
    source: 'Per-tour group definitions',
    realSource: 'manual_entry',
    phase: 'advance',
    detail:
      'Primary groups (Artist, A Party, Mgmt, Audio, Lighting, Video, Backline) are mostly identical across tours — copy-from-previous helps.',
  },
  group_tag: {
    source: 'Sub-groups inside a Group',
    realSource: 'manual_entry',
    phase: 'advance',
    detail:
      'Daysheets-style sub-groups (Audio → FOH vs Audio → Monitors) so visibility/notifications can target precisely without admin re-tagging.',
  },

  // ----- Daily ops --------------------------------------------
  schedule_item: {
    source: 'Advance with venue PM + template-driven entry',
    realSource: 'manual_entry',
    phase: 'advance',
    detail:
      'Load-in, soundcheck, doors, set, curfew, load-out times are agreed between PM and venue PM in advance emails. Templates ("Arena Show Day") pre-fill common shapes; one click applies.',
  },
  travel: {
    source: 'Travel agent + AI flight-PDF ingest',
    realSource: 'ai_extraction',
    phase: 'advance',
    detail:
      'Travel agent emails confirmation PDFs. User drops the PDF into the hub; Claude extracts a structured Flight/Travel object; TM reviews side-by-side and approves. v1 supports flights, bus, drive, ferry, train.',
  },
  hotel: {
    source: 'Travel agent + manual block confirmation',
    realSource: 'manual_entry',
    phase: 'advance',
    detail:
      'Hotel blocks are negotiated by the travel agent. Block confirmations come in as PDFs or spreadsheets. Hotel addresses for the artist are *sensitive* and auto-redacted on posted/printed day sheets.',
  },
  task: {
    source: 'TM/PM in-app entry',
    realSource: 'manual_entry',
    phase: 'ongoing',
    detail:
      'Ad-hoc tasks attached to a day or floating. Often created in response to a chat message — future Slack/SMS integration would auto-create tasks from "@TM remember to ..." messages.',
  },

  // ----- Documents --------------------------------------------
  document_rider: {
    source: 'Artist/PM rider PDF + AI section extraction',
    realSource: 'document_upload',
    phase: 'advance',
    detail:
      'The rider PDF is uploaded as-is. Claude classifies which sections are present, then per-section extractors pull structured data (input list, labor call, schedule). Original PDF is always preserved. Live link per show always serves the current revision (Showvella-style).',
  },

  // ----- AI ingest --------------------------------------------
  flight_import: {
    source: 'AI extraction from uploaded confirmation PDF',
    realSource: 'ai_extraction',
    phase: 'advance',
    detail:
      'User drags flight PDFs into upload zone. Server stores in R2, sends base64 + structured-output prompt to Claude Sonnet. Returns typed Flight object. Review UI shows PDF on left, parsed data on right. Passenger names matched to existing TourPerson records.',
  },
  rider_import: {
    source: 'AI section-by-section extraction from rider PDF',
    realSource: 'ai_extraction',
    phase: 'advance',
    detail:
      'Two-step pipeline: (1) classifier identifies which sections are present, (2) per-section structured-output extractors run. Multi-language: parse-in-language, present bilingually (original + English translation per field). Each section reviewed independently in side-by-side UI before approval.',
  },

  // ----- Per-rider-section provenance (everything below this
  //       is "AI-extracted from this rider PDF"; in the mock data
  //       these values are pulled from the real Elsa y Elmar
  //       rider via the handoff doc and are real, but the UI
  //       MockTag wrapping is for OTHER sections that haven't
  //       been wired to extractors yet).
  rider_cover_contacts: {
    source: 'Rider cover page — AI extraction',
    realSource: 'ai_extraction',
    phase: 'advance',
    detail:
      'Step 1 of the pipeline (classifier) returns artist_name, revision_info, and production_manager contact (name, email, phone) from page 1.',
  },
  rider_input_list: {
    source: 'Rider §6 — AI extraction',
    realSource: 'ai_extraction',
    phase: 'advance',
    detail:
      'Highest-value section. Step 2 extractor returns 44 channels with verbatim source labels, mic/DI models, stand types, phantom power flags. Extraction flags surface duplicates / missing data for human review.',
  },
  rider_monitor_mix: {
    source: 'Rider §6 monitor outputs — AI extraction',
    realSource: 'ai_extraction',
    phase: 'advance',
    detail:
      '8 stereo monitor mixes parsed from the input-output table. Person names (Elsa, Juan, Daniel, Julian) are cross-referenced against the personnel extractor.',
  },
  rider_foh_outputs: {
    source: 'Rider §6 FOH output patch — AI extraction',
    realSource: 'ai_extraction',
    phase: 'advance',
    detail:
      '8 FOH outputs (SMPTE, talkback speaker, light & video mix, main LR, sub, front fill) parsed from the input-output table.',
  },
  rider_stage_specs: {
    source: 'Rider §4 — AI extraction',
    realSource: 'ai_extraction',
    phase: 'advance',
    detail:
      'Stage dimensions, ground support, barricade requirements, generators/power, ambulance requirement.',
  },
  rider_audio_pa: {
    source: 'Rider §5 — AI extraction',
    realSource: 'ai_extraction',
    phase: 'advance',
    detail:
      'PA system specifications, SPL targets, brand alternates, console preferences, monitor system, RF system.',
  },
  rider_stage_plot: {
    source: 'Rider §7 — AI vision extraction',
    realSource: 'ai_extraction',
    phase: 'advance',
    detail:
      'Stage plot is a visual diagram — sent to Claude as an image, returns performer positions, instruments, monitor placements. Lower accuracy than text sections (~70-80%); UI lets human drag to correct.',
  },
  rider_lighting: {
    source: 'Rider §8 — AI extraction',
    realSource: 'ai_extraction',
    phase: 'advance',
    detail:
      'Lighting equipment list + truss + power. CAD pages are stored as attached references only; v1 does not extract structure from drawings.',
  },
  rider_backline: {
    source: 'Rider §9 — AI extraction',
    realSource: 'ai_extraction',
    phase: 'advance',
    detail:
      'Drums, bass, guitar, miscellaneous. Schema captures both preferred and EXCLUDED brands ("NOT Yamaha hi-hat stand", "NOT motorcycle seat"). Negative constraints are as important as positive specs.',
  },
  rider_soundcheck: {
    source: 'Rider §10 — AI extraction',
    realSource: 'ai_extraction',
    phase: 'advance',
    detail:
      'Closed-door soundcheck requirement, minimum hours from load-in.',
  },
  rider_transport: {
    source: 'Rider §11 — AI extraction',
    realSource: 'ai_extraction',
    phase: 'advance',
    detail:
      'Ground transport (vans, cargo) + air transport ticket counts and class requirements. Sourced by travel agent against these specs.',
  },
  rider_lodging: {
    source: 'Rider §12 rooming list — AI extraction',
    realSource: 'ai_extraction',
    phase: 'advance',
    detail:
      'Rooming list reveals the touring party roster. 10 rooms for 11 occupants. Names where given; role placeholders where not. Used by personnel cross-reference resolver.',
  },
  rider_dressing_rooms: {
    source: 'Rider §13 — AI extraction',
    realSource: 'ai_extraction',
    phase: 'advance',
    detail:
      'Dressing room requirements — dimensions, contents, hospitality items. Excluded items ("no roses or sunflowers") are captured.',
  },
  rider_catering: {
    source: 'Rider §14 — AI extraction',
    realSource: 'ai_extraction',
    phase: 'advance',
    detail:
      '7 menus across 3 dressing rooms by time-of-day (load-in, soundcheck, show, post-show). Excluded brands captured ("no Sol or Corona"). Dietary tags, biodegradable requirements, donation plans.',
  },
  rider_conflicts: {
    source: 'Conflict detector (derived after extraction)',
    realSource: 'derived',
    phase: 'advance',
    detail:
      'Runs after all section extractors complete. Flags contradictions, missing references, count mismatches. The parser does not auto-resolve — humans always decide.',
  },

  // ----- Scratch mode (Start From Scratch onboarding) ---------
  scratch_tour: {
    source: 'Start From Scratch onboarding mode',
    realSource: 'manual_entry',
    phase: 'booking',
    detail:
      'In scratch mode the app starts as an empty tour a new TM builds up by uploading the project mock fixtures. Uploads are matched by filename to known sample files — there is no backend parsing yet. See CLAUDE.md "Data modes".',
  },
  route_import: {
    source: 'Booking-agent routing CSV — scratch-mode import',
    realSource: 'csv_import',
    phase: 'booking',
    detail:
      'The routing spreadsheet builds a Day per row, sets each day type, attaches venues to show days, and seeds a show-day schedule skeleton (load-in, soundcheck +6h, doors, set, curfew). In production this is the same CSV the booking agent sends with the deal memo.',
    artifacts: [
      { label: 'Mock 7-day route (Mexico leg)', url: '/mock-tour-route-mexico-7day.csv', kind: 'csv' },
    ],
  },

  // ----- Cross-cutting ---------------------------------------
  visibility: {
    source: 'Per-item attribute spec set by item owner',
    realSource: 'manual_entry',
    phase: 'advance',
    detail:
      'Visibility is ABAC, not RBAC. Each schedule item / travel / hotel / task / doc has a visibility blob: default + group overrides + tag overrides + person overrides. Most specific wins. Postgres RLS enforces in DB, never in app layer.',
  },
  audit_trail: {
    source: 'Database audit columns (updated_at / updated_by)',
    realSource: 'system',
    phase: 'ongoing',
    detail:
      'Every record carries updated_at / updated_by columns the database writes on each save, backed by an append-only change log. In this prototype the seeded history is mock; in-app actions like locking a day stamp the current demo viewer against the pinned demo clock (Sep 25, 2025).',
  },
  settlement: {
    source: 'Box office settlement + tour accounting',
    realSource: 'manual_entry',
    phase: 'settlement',
    detail:
      'Promoter rep settles with TM each night. Ticket counts, walk-up, comps, fees, splits, taxes, expenses. Wide-open product area — most tour accountants still use Excel.',
  },
  truck_tracking: {
    source: 'HET Hub or similar telemetry integration',
    realSource: 'external_api',
    phase: 'show_day',
    detail:
      'Real-time truck position + ETA for 50-90 truck convoys at arena/stadium scale. Embed in PM dashboard so they know where every truck is.',
  },
} satisfies Record<string, Provenance>;

export type SourceKey = keyof typeof sources;

export function getSource(key: SourceKey): Provenance {
  return sources[key] as Provenance;
}

// Helper to pretty-print a real-source enum for the UI
export const realSourceLabels: Record<RealSource, string> = {
  manual_entry: 'Manual entry',
  csv_import: 'CSV / spreadsheet import',
  ai_extraction: 'AI extraction (Claude)',
  document_upload: 'Document upload',
  external_api: 'External API',
  derived: 'Derived',
  system: 'System-generated',
};

export const phaseLabels: Record<LifecyclePhase, string> = {
  booking: 'Booking phase',
  advance: 'Advance phase',
  rehearsal: 'Rehearsal phase',
  show_day: 'Show day',
  settlement: 'Settlement',
  ongoing: 'Ongoing',
};
